//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IziCast.Core.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("IziCast.Core.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string VideoSenderService_NoPlayersAvailable {
            get {
                return ResourceManager.GetString("VideoSenderService.NoPlayersAvailable", resourceCulture);
            }
        }
        
        public static string OverlayPermissionService_NeedToEnablePermission {
            get {
                return ResourceManager.GetString("OverlayPermissionService.NeedToEnablePermission", resourceCulture);
            }
        }
        
        public static string MainViewModel_Title {
            get {
                return ResourceManager.GetString("MainViewModel.Title", resourceCulture);
            }
        }
        
        public static string MainViewModel_DataHint {
            get {
                return ResourceManager.GetString("MainViewModel.DataHint", resourceCulture);
            }
        }
        
        public static string DataHint {
            get {
                return ResourceManager.GetString("DataHint", resourceCulture);
            }
        }
        
        public static string ViewModels_MainViewModel_DataHint {
            get {
                return ResourceManager.GetString("ViewModels.MainViewModel.DataHint", resourceCulture);
            }
        }
        
        public static string IziCast_Core_ViewModels_MainViewModel_DataHint {
            get {
                return ResourceManager.GetString("IziCast.Core.ViewModels.MainViewModel.DataHint", resourceCulture);
            }
        }
    }
}
